import type { Analysis, Insight, PageText, StoredDocument, SummaryLength } from '../types.js';
import { keywords, relevant, sentences } from '../utils/text.js';
const counts:{[key in SummaryLength]:number}={short:4,medium:7,long:11};
const full=(pages:PageText[])=>pages.map(x=>`Page ${x.page}\n${x.text}`).join('\n\n');
const extractSummary=(text:string,length:SummaryLength)=>{const source=sentences(text),n=counts[length];return Array.from({length:n},(_,i)=>{const start=Math.floor(i*source.length/n),end=Math.max(start+1,Math.floor((i+1)*source.length/n));return source.slice(start,end).sort((a,b)=>b.length-a.length)[0];}).filter(Boolean).join(' ');};
const scan=(document:StoredDocument):Insight=>{const text=full(document.pages), dates=[...new Set(text.match(/\b(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2},?\s+\d{4}\b|\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b/g)||[])].slice(0,6), people=[...new Set(text.match(/\b[A-Z][a-z]+\s+[A-Z][a-z]+\b/g)||[])].slice(0,6), orgs=[...new Set(text.match(/\b[A-Z][A-Za-z]+\s+(?:Inc|Ltd|LLC|University|Corporation|Corp|Committee)\b/g)||[])].slice(0,6), numbers=[...new Set(text.match(/\b(?:\$|€|£)?\d[\d,.]*%?\b/g)||[])].slice(0,8); return {pages:document.pages.length,words:text.trim().split(/\s+/).length,readingMinutes:Math.max(1,Math.ceil(text.trim().split(/\s+/).length/230)),documentType:document.mimeType==='application/pdf'?'PDF':'Image',ocrUsed:document.ocrUsed,topics:keywords(text),dates,people,organizations:orgs,numbers};};
export class AIService{
  async analyze(document:StoredDocument,length:SummaryLength='medium'):Promise<Analysis>{const text=full(document.pages), all=sentences(text), summary=extractSummary(text,length), actionItems=all.filter(s=>/\b(shall|must|should|need to|action|required|submit|review|schedule|deadline|due)\b/i.test(s)).slice(0,5), suggestions=[] as {category:string;text:string}[]; if(all.some(s=>s.split(/\s+/).length>35))suggestions.push({category:'Clarity',text:'Some sentences are dense. Splitting long ideas into shorter sentences would improve scanability.'}); if(!/\b(conclusion|summary|next steps)\b/i.test(text))suggestions.push({category:'Structure',text:'Consider adding a concise conclusion or next-steps section for faster decision making.'}); if(!suggestions.length)suggestions.push({category:'Readability',text:'The document is structured clearly. Keep headings and concrete facts prominent for reviewers.'}); return {summary,keyPoints:all.slice(0,Math.min(5,all.length)),insights:scan(document),actionItems,suggestions};}
  async answer(document:StoredDocument,question:string){const chunks=relevant(document.pages,question); const questionWords=(question.toLowerCase().match(/[a-z]{3,}/g)||[]); const candidates=chunks.flatMap(c=>sentences(c.text).map(sentence=>({page:c.page,sentence,score:questionWords.filter(w=>sentence.toLowerCase().includes(w)).length}))).sort((a,b)=>b.score-a.score).slice(0,3); if(!candidates.length||candidates[0].score===0)return {answer:'I could not find a grounded answer to that question in this document.',sources:[]}; return {answer:candidates.map(x=>x.sentence).join(' '),sources:[...new Map(candidates.map(x=>[x.page,{page:x.page,excerpt:x.sentence.slice(0,220)}])).values()]};}
}
